### ISSUE TITLE
Mistake. Plugin not working.

### ISSUE THREAD

**Issue by winitop** [mick912/oc-vklogin-plugin#1]
After installing plug-in, when you go to the settings, an error occurs:

> Class 'Socialite' not found

The same problem with the plugin OK Login

**Comment by mick912** [comment]
Hello.
Did you install Flynsarmy.SocialLogin(https://octobercms.com/plugin/flynsarmy-sociallogin) plugin?

**Comment by winitop** [comment]
На русском можно отвечать или лучше переводить на английский?

Да, я ставил сначала плагин SocialLogin а за тем плагины для ВК и ОК.
SocialLogin становится и работает, а после установки ВК - при заходе в настройки плагина (там где ключи) выдаётся ошибка.

Я ждал ответа, потом удалил все эти плагины так как не смог найти решения. Без ВК я не хочу ставить вход через другие соцсети.

Если подскажите как решить проблему, я могу заново установить все эти плагины.

**Comment by mick912** [comment]
Похоже автолоадер плагина не влючается oc-vklogin-plugin/blob/master/vendor/autoload.php.
1. Проверьте есть ли файлы oc-vklogin-plugin/tree/master/vendor/laravel/socialite
2. Если нет, то попрубуйте зайти в папку плагина и запустить php composer install

**Comment by winitop** [comment]
> Проверьте есть ли файлы oc-vklogin-plugin/tree/master/vendor/laravel/socialite

А где их проверить?
Я установил плагин vklogin, теперь при заходе в настройки SocialLogin у меня 500 ошибка. Если выключаю плагин, то настройки SocialLogin доступны.

Вот папка плагина после установки:
![screen-vk_login](https://user-images.githubusercontent.com/32765749/67635589-a022cf80-f8d1-11e9-99e4-815a4af713b5.jpg)

**Comment by winitop** [comment]
Похоже вот это папка установилась:
![screen-vk_login_2](https://user-images.githubusercontent.com/32765749/67635684-3e169a00-f8d2-11e9-8056-3d233268c499.jpg)
Это автоматом само встало при установке плагина (без команды композера).

**Comment by mick912** [comment]
Подробнее об окружение отправьте. 
1. Какая версия октября?
2. php?
3. включите debug режим в настройках. 
4. отправьте полный стек ошибки

**Comment by igor-tv** [comment]
OctoberCMS 458, php 7.3

Class 'Socialite' not found
/home/l/.../public_html/plugins/mirjan/vklogin/socialloginproviders/Vk.php line 25

TYPE
Undefined

EXCEPTION
Symfony\Component\Debug\Exception\FatalThrowableError


`
# | CALLED CODE | DOCUMENT | LINE
-- | -- | -- | --
56 | Mirjan\Vklogin\SocialLoginProviders\Vk->init() | ~/vendor/october/rain/src/Support/Traits/Singleton.php | 39
55 | Mirjan\Vklogin\SocialLoginProviders\Vk->__construct() | ~/vendor/october/rain/src/Support/Traits/Singleton.php | 23
54 | Mirjan\Vklogin\SocialLoginProviders\Vk::instance() | ~/plugins/flynsarmy/sociallogin/Plugin.php | 92
53 | Flynsarmy\SocialLogin\Plugin->Flynsarmy\SocialLogin\{closure}(…) |   |  
52 | call_user_func_array(…) | ~/vendor/october/rain/src/Events/Dispatcher.php | 233
51 | October\Rain\Events\Dispatcher->dispatch(…) | ~/vendor/october/rain/src/Events/Dispatcher.php | 197
50 | October\Rain\Events\Dispatcher->fire(…) | ~/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php | 221
49 | Illuminate\Support\Facades\Facade::__callStatic(…) | ~/modules/system/traits/EventEmitter.php | 58
48 | Backend\Classes\WidgetBase->fireSystemEvent(…) | ~/modules/backend/widgets/Form.php | 603
47 | Backend\Widgets\Form->defineFormFields() | ~/modules/backend/widgets/Form.php | 153
46 | Backend\Widgets\Form->bindToController() | ~/modules/system/controllers/Settings.php | 154
45 | System\Controllers\Settings->initWidgets(…) | ~/modules/system/controllers/Settings.php | 86
44 | System\Controllers\Settings->update(…) |   |  
43 | call_user_func_array(…) | ~/modules/backend/classes/Controller.php | 397
42 | Backend\Classes\Controller->execPageAction(…) | ~/modules/backend/classes/Controller.php | 285
41 | Backend\Classes\Controller->run(…) | ~/modules/backend/classes/BackendController.php | 161
40 | Backend\Classes\BackendController->run(…) |   |  
39 | call_user_func_array(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php | 54
38 | Illuminate\Routing\Controller->callAction(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php | 45
37 | Illuminate\Routing\ControllerDispatcher->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 212
36 | Illuminate\Routing\Route->runController() | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 169
35 | Illuminate\Routing\Route->run() | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 658
34 | Illuminate\Routing\Router->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
33 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/modules/backend/classes/BackendController.php | 68
32 | Backend\Classes\BackendController->Backend\Classes\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 131
31 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
30 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php | 41
29 | Illuminate\Routing\Middleware\SubstituteBindings->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
28 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
27 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php | 49
26 | Illuminate\View\Middleware\ShareErrorsFromSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
25 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
24 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php | 63
23 | Illuminate\Session\Middleware\StartSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
22 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
21 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php | 37
20 | Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
19 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
18 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 66
17 | Illuminate\Cookie\Middleware\EncryptCookies->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
16 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
15 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
14 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 660
13 | Illuminate\Routing\Router->runRouteWithinStack(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 635
12 | Illuminate\Routing\Router->runRoute(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 601
11 | Illuminate\Routing\Router->dispatchToRoute(…) | ~/vendor/october/rain/src/Router/CoreRouter.php | 20
10 | October\Rain\Router\CoreRouter->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 176
9 | Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
8 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php | 46
7 | Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…) | ~/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php | 24
6 | October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
5 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
4 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
3 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 151
2 | Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 116
1 | Illuminate\Foundation\Http\Kernel->handle(…) | ~/index.php | 43

`

**Comment by mick912** [comment]
починил. установите новую версию.
причина была в том что, плагин flynsarmy-sociallogin v 1.0.23 перешел на HybridAuth
